#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "halcyon"
name = "Halcyon"
description.en = "Webclient for Mastodon and Pleroma"
description.fr = "Client web pour Mastodon et Pleroma"

version = "2.4.9~ynh3"

maintainers = []

[upstream]
license = "AGPL-3.0-only"
website = "https://notabug.org/halcyon-suite/halcyon"
code = "https://notabug.org/halcyon-suite/halcyon"
cpe = "cpe:2.3:a:halcyon_project:halcyon"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["en_US", "de_DE", "pt_BR", "ja_JP", "ko_KR", "pl_PL", "gl_ES", "fr_FR", "cs_CZ", "it_IT"]
    default = "en_US"

[resources]
    [resources.sources.main]
    url = "https://notabug.org/halcyon-suite/halcyon/archive/2.4.9.tar.gz"
    sha256 = "5fa0b6f9bb850b4d94f4d210887559fccf9f230baa898f03f7f167c29f3c8c1e"

    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "php7.4-intl",
        "php7.4-mbstring",
        "php7.4-curl",
        "php7.4-json",
        "php7.4-gettext",
    ]
