#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    test_upgrade_from.7716f1b2c8260239b55470c6e1235b86e73dd034.name = "2.4.9~ynh2"
